### PR TITLE
Update suspend-modules.conf

### PR DESCRIPTION
**Pull request by CGarces**
Add 8189es

### CODE REVIEW

**Comment by CGarces** [comment]
I'm not 100% sure about this.
Suspend not works on my device so I can't test the benefits, but if you are putting some WiFi modules, made sense put others too. Right?

**Comment by kszaq** [comment]
This is not needed at all. Unloading `cfg80211` forces unloading all WiFi modules, including 8189es. Previous entries in this file are from stock LE configuration file.

**Comment by CGarces** [comment]
So why you have 8812au and not 8189es ? it confuse me.

**Comment by kszaq** [comment]
Like I said above, current project-specific file is stock LE + `cfg80211`: https://github.com/kszaq/LibreELEC.tv/blob/libreelec-7.0/packages/sysutils/busybox/config/suspend-modules.conf

**Comment by CGarces** [comment]
ok, understood. So wifi modules not are need at all due cfg8021, but remove it not provide an real benefit (just cosmetic).

**Pull request closed without merging**
