### PR TITLE
Fix remote config

### PR DESCRIPTION
**Pull request by CGarces**
My remote stop working with some keys after the last changes on remote config

Was caused by the regular expression used. For example:

**97$**

That expression is looking for the number 97 + end of line 

But not match with the [remote that comes on my Android device](https://github.com/CGarces/SCISHIONV88PRO/blob/master/ir/remote.conf) 
**0x11 97#ok**

Note the "#" caracter used for coments

The regular expression should be changed to:

**\s97(#.*|$)**

That search for the specific number (97) followed by a comment or end of line.

Match with "97" or "97#ok" but not with "197" or "971"

Test it online at https://regex101.com/r/C152Rd/1

### CODE REVIEW

**Comment by CGarces** [comment]
My remote stop working to some keys after the last changes on remote config

Was caused by the regular expression used. For example:

**97$**

That expression is looking for the number 97 + end of line 

But not match with the [remote that comes on my Android device](https://github.com/CGarces/SCISHIONV88PRO/blob/master/ir/remote.conf) 
**0x11 28#ok**

Note the "#" caracter used for coments

The regular expression should be changed to:

**\s97(#.*|$)**

That search for the specific number (97) followed by a comment or end of line.

Match with "97" or "97#ok" but not with "197" or "971"

Test it online at https://regex101.com/r/C152Rd/1

**Comment by kszaq** [comment]
Thank you for your patch.

I use a bit different approach in my development builds:
- here is the latest dev build commit list: https://github.com/kszaq/LibreELEC.tv/commits/2016-10-24-devel
- a fix: https://github.com/kszaq/LibreELEC.tv/commit/a00b33727eee010bb5ea033345aba452919f3507

The issue with your approach is that it doesn't match numbers if there's anything other than `#` or newline after a number to match: there are files where there's a single or more spaces after the number. The regex in my approach is uglier but it seems to work for all cases.

**Comment by CGarces** [comment]
LoL all my work is useless

And you also have backported this!
https://github.com/kszaq/LibreELEC.tv/commit/57856b70b7223f947dfd239fd5369a1362ef6ff0

See the comment from  codesnake
https://forum.libreelec.tv/thread-2096-post-16858.html#pid16858

**Comment by kszaq** [comment]
Not useless, I learned some regex-fu thanks to you today. ;)

And you didn't know I fixed it as there were no commits pushed here.

The backport is for testing. :)

**Pull request closed without merging**
