### PR TITLE
Use mainstream modules

### PR DESCRIPTION
**Pull request by CGarces**
This PR disable some modules from kernel to use the mainstream code at packages/linux-drivers/

It allow to maintain the code up to date and sync with LibreElec repository.

I have send this PR over libreelec-7.0 with the last changes from tags, but I can rebase the PR if needed.

You can obtain a similar PR using this cherry-pick

`git cherry-pick c637a0200a5ac6a19a79adc112ab831caea91f86 c80df2f000d0b735e9040414a87d53a41d5eb101 23037b828804fa47d2e7d29c4f60951c6329a14e 6b94a15ae933ab34eafb2ad9e4f196c7f2b69d9a a3dca5031b21f4a12bd303e4cb0517ef030b9282
`
And the additional changes from 005677ff7492ca0aa2f56d9b547d8de02c203e6a

I have compiled and tested on my S905 device unfortunately has a rtl8189es so I can't test the modules by myself.
If you think that is PR is useful, I can continue the work creating a module for other drivers like rtl8189es, the one used by my android device.

### CODE REVIEW

**Comment by kszaq** [comment]
Thank your the PR. Can you rebase this on my `libreelec-7.0` branch? Or you can wait for me to push the changes from development tags to this branch. I do not want to use all commits from tags as I sometimes change them (fixups etc.) before pushing into release.

I'm also not sure whether we want to use 8188EU driver from packages as it was reported to not work well with built-in chips.

**Comment by CGarces** [comment]
Done, only two drivers changed RTL8192EU and RTL8812AU.

You have any device with 8188EU to reproduce the error?
Are you interested in a new module for rtl8189es?

Just FYI RTL8188EU [was removed](https://github.com/OpenELEC/OpenELEC.tv/commit/d8d1aa97b7b54043d8b6bcd42eaefd80d7dc43fe) from OpenELEC I can't find more information.

**Comment by CGarces** [comment]
Added RTL8189ES as package. Tested on my S905X device.
The source code has been fetched from the kernel.

**Comment by kszaq** [comment]
Thank you! This will certainly be useful when mainstreaming S805 and S905 projects. :+1:

**Comment by CGarces** [comment]
Added 3 new packages
RTL8189FS, RTL8723BS and RTL8822BU
I don't have the proper hardware to test it, but the code comes from the kernel, so must work.
I haven't added it to the options file due lack of testing

**Comment by kszaq** [comment]
@CGarces Thank you a lot for your input. I think at this point I will cherry-pick your commits to use upstream drivers if that's OK? For Amlogic-specific drivers there are 2 things I would like to change:
- use repositories with commit history: you can find drivers at https://github.com/tomatotech/mmallow_hardware_wifi_realtek_drivers_8189es https://github.com/tomatotech/mmallow_hardware_wifi_realtek_drivers_8189ftv https://github.com/tomatotech/mmallow_hardware_wifi_realtek_drivers_8188ftv https://github.com/tomatotech/mmallow_hardware_wifi_realtek_drivers_8188eu 
- rename packages to RTLxxxxxx-aml to make them look Amlogic-specific.

**Comment by CGarces** [comment]
No problem, if you cherry-pick the commits I will remove it from the PR.

If you think that use RTLxxxxxx-aml is better, it's ok for me,

Drivers from https://github.com/CGarces/RTL* are from your kernel code so you have a 99% possibilities to success.  We can use it as backup plan if mmallow_hardware_wifi_realtek_drivers_\* not works.

I'll do it ASAP.

**Comment by kszaq** [comment]
No rush. :)

**Comment by CGarces** [comment]
After learn how rebase commits.... done.
I have only tested RTL8189ES.
Added also RTL8188EU-AML that replace the upstream driver

**Comment by kszaq** [comment]
@CGarces I cherry-picked your first commits to `libreelec-7.0` branch. I did not have time to test other commits. They look good but need to be tested before I merge them into release build.

**Comment by CGarces** [comment]
Rebased

**Comment by CGarces** [comment]
supersede by 2d049560e57a1b988d684026d2e8b8d4194fa89b

**Comment by kszaq** [comment]
@CGarces once again I'd like to thank you for this PR. Only recently have I had time to merge it and I decided to rework it to use as few patches as possible (none actually) and more up-to-date repos. I based it partially on your work, I hope you're not angry that I did not merge the PR.

**Comment by CGarces** [comment]
I'm more than happy to have a updated version of  RTL8189ES

**Pull request closed without merging**
