### PR TITLE
Libreelec 7.0

### PR DESCRIPTION
**Pull request by meijjaa**
Hi Kszak,

The bluez-07-broadcom-dont-set-speed-before-loading.patch doesn't seem to to anything and will just slow down the init process. I would like to suggest to replace it with my patch to fix the timeout during reset after firmware upload.

### CODE REVIEW

**Comment by kszaq** [comment]
Thank you for the patches!

I believe that we had timeout errors because the firmware loading service was loaded too early. I am trying to fix it in c00126edc8785079d4f554e92b6e760baf0c5b2f. If after this patch it still doesn't work, I will merge your suggestions.

**Comment by meijjaa** [comment]
I actually was testing on an already running system so I'm afraid this won't help. My patch feels a bit hacky but this is the way that brcm_patchram_plus also does it.

**Comment by kszaq** [comment]
Could you possibly check 7.0.3.012f build (or tag if you're building yourself)?

**Comment by meijjaa** [comment]
No problem, I downloaded your 012f build to be sure but it still doesn't work. 

Everything else is working great by way :) _(only some buffering / audio drop issues with live tv (tvheadend). Maybe this commit? https://github.com/kszaq/LibreELEC.tv/commit/24660e116daf9cab9d2cbfae49a1227c3d1bff71 )_

**Comment by kszaq** [comment]
Okay, thanks for testing. Since I also want to use hciattach instead of brcm_patchram in my S805 builds, I will cherry-pick your patch as a bluez patch. Of course I will keep your authorship.

**Comment by kszaq** [comment]
I cherry-picked your patch to my libreelec-7.0 branch: https://github.com/kszaq/LibreELEC.tv/commit/3a478ad0f1b494d5e065b1b7762e7908f1a8938a. Can you please try 7.0.3.012g build and confirm if it;s OK now?

**Comment by meijjaa** [comment]
It works now and you also solved the buffer problem, keep up the good work! 

I'll close the pull request now.

**Comment by kszaq** [comment]
Thank you for your contribution!

**Pull request closed without merging**
