### PR TITLE
projects/S905: Delete cputemp

### PR DESCRIPTION
**Pull request by CGarces**
File not need, contains the same code than packages/mediacenter/kodi/scripts/cputemp

### CODE REVIEW

**Comment by CGarces** [comment]
Current cputemp contains same code than packages/mediacenter/kodi/scripts/cputemp

```
  # used on some intel systems
  if [ "$TEMP" = "0" -a -f /sys/devices/virtual/thermal/thermal_zone0/temp ]; then
    TEMP=`cat /sys/devices/virtual/thermal/thermal_zone0/temp`
  fi

  # used on RaspberryPi
  if [ "$TEMP" = "0" -a -f /sys/class/thermal/thermal_zone0/temp ]; then
    TEMP=`cat /sys/class/thermal/thermal_zone0/temp`
  fi
```

In any case not is working on S905X

**Comment by kszaq** [comment]
The script is not 100% the same as the project-specific one doesn't divide returned temperature value by 1000.

On the other hand, you are correct that this file is not needed as Amlogic 3.14 kernel returns temperature value in millicelsius. 

 I have 2 requests to this PR: please also delete Kodi patch for temperature scaling and reword commit message to include "projects/S905". Thanks.

If you want to make temperature sensor work, you can enable it in kernel config. It will work for S905X but with S905 the only thing you get is spammed kmsg - that's the reason why I don't enable it for my builds.

**Comment by CGarces** [comment]
So projects/S905/patches/kodi/ct-001-fix_cpu_usage_in_the_osd.patch is no longer needed?

**Comment by kszaq** [comment]
Thank you!

**Comment by CGarces** [comment]
Works fine on S905X after compile again the kernel.
Maybe it's possible filter the cputemp output based on the /proc/cpuinfo (020a on S905X) please confirm this approach because I don't have a S905 device.

**Comment by kszaq** [comment]
The issue with S905 is not in `cputemp` - it's in kernel thermal driver.

**Comment by CGarces** [comment]
Let me understand the problem.

You not compile that option in the kernel because get incorrect information for S905, but works fine for S905X

My proposed solution is compile the kernel with the  temperature sensor, and create a new cputemp that only return values for the revision 020a that I assume that should match only with S905X

Something like this (I haven tested the code sorry I'll do latter)

```
#Hack for S905x
VERSION=cat /proc/cpuinfo | grep "Revision" | sort -u | cut -d: -f2
if [ "$VERSION" == "020a" ]; then
    TEMP=`cat /sys/class/thermal/thermal_zone0/temp`
fi
```

This will get a value at least for S905X, fix the kernel thermal driver is out of my skills. But I need to confirm that the "Revision" approach is the correct way to identify the S905X over the S905

**Comment by kszaq** [comment]
No. The issue is that if you compile kernel with TEMP_SENSOR enabled, kernel log is spammed with thermal driver messages. It is not a big issue for a user but for me it makes debugging very unpleasant. I may disable thermal driver for S905 in `platform_init` but I would prefer to have temperature sensor fixed.

**Pull request merged**
